apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-configmap.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-persistent-volume.yaml
  - postgres-deployment.yaml
