ALTER TABLE owners ADD COLUMN name VARCHAR(255);
ALTER TABLE owners ADD COLUMN address VARCHAR(255);
ALTER TABLE owners ADD COLUMN city VARCHAR(255);
ALTER TABLE owners ADD COLUMN telephone VARCHAR(255);
ALTER TABLE owners ADD COLUMN pets VARCHAR(255);

ALTER TABLE vets ADD COLUMN name VARCHAR(255);
ALTER TABLE vets ADD COLUMN specialties VARCHAR(255);

