version: '3'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://172.17.0.11:5432/petclinic -schemas=petclinic -user=postgres -password=12Postgres@! -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=12Postgres@!
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 5432:5432