apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: petclinic
  labels:
    app: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyway
  namespace: petclinic
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: thevestedleopard/flyway
          args:
            - info
            - repair
            - migrate
            - info
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://172.17.0.11:5432/petclinic
            - name: FLYWAY_USER
              value: postgres
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: FLYWAY_PLACEHOLDER_REPLACEMENT
              value: "true"
            - name: FLYWAY_PLACEHOLDERS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: petclinic-configmap
                  key: spring.datasource.username
            - name: FLYWAY_PLACEHOLDERS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petclinic-secret
                  key: spring.datasource.password
          volumeMounts:
          - name: sql
            mountPath: /flyway/sql
            subPath: sql
      volumes:
        - name: sql
          configMap:
            name: postgres-configmap
      restartPolicy: Never