apiVersion: v1
data:
  POSTGRES_DB: petclinic
  POSTGRES_PASSWORD: MTJQb3N0Z3Jlc0Ah
  POSTGRES_USER: postgres
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: petclinic
---
apiVersion: v1
data:
  password: MTJQb3N0Z3Jlc0Ah
kind: Secret
metadata:
  name: postgres
  namespace: petclinic
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: petclinic
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres
        envFrom:
        - configMapRef:
            name: postgres-config
        image: postgres:latest
        name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
          subPath: postgres
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: pv-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/lib/postgresql/data
  storageClassName: local-storage
