apiVersion: v1
kind: Service
metadata:
  name: petclinic-application
  namespace: petclinic
  labels:
    app: petclinic-application
spec:
  type: NodePort
  selector:
    app: petclinic-application
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30007