apiVersion: v1
kind: Service
metadata:
  name: petclinic-application
  namespace: petclinic
  labels:
    app: petclinic-application
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
      name: http
  selector:
    app: petclinic-application

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: petclinic-configmap
  namespace: petclinic
data:
  spring.datasource.url: jdbc:postgresql://postgres:5432/petclinic
  spring.datasource.username: postgres
  spring.datasource.password: 12Postgres@!
  spring.datasource.driver-class-name: org.postgresql.Driver
  spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  spring.jpa.show-sql: "false"
  spring.jpa.hibernate.ddl-auto: create
  spring.jpa.open-in-view: "false"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-application
  namespace: petclinic
  labels:
    app: petclinic-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-application
  template:
    metadata:
      labels:
        app: petclinic-application
    spec:
      containers:
        - name: petclinic
          image: thevestedleopard/springboot-docker:latest
          ports:
          - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
