apiVersion: v1
kind: Service
metadata:
  name: petclinic-application
  namespace: petclinic
  labels:
    app: petclinic-application
spec:
  type: NodePort
  selector:
    app: petclinic-application
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-application
  namespace: petclinic
  labels:
    app: petclinic-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-application
  template:
    metadata:
      labels:
        app: petclinic-application
    spec:
      containers:
        - name: petclinic
          image: thevestedleopard/springboot-docker:latest
          ports:
          - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
