apiVersion: v1
kind: Service
metadata:
  name: petclinic-application
  namespace: petclinic
  labels:
    app: petclinic-application
spec:
  type: NodePort
  selector:
    app: petclinic-application
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30007
---
apiVersion: v1
kind: Pod
metadata:
  name: petclinic-application
  namespace: petclinic
  labels:
    app: petclinic-application
spec:
  containers:
  - name: petclinic-app
    image: thevestedleopard/springboot-docker:latest
    ports:
      - containerPort: 8080
    command: ["sleep", "3600"]
    env:
      # Define the environment variable
      - name: SPRING-APP-CONFIG # the case is different here from the key name in the configmap
        valueFrom:
        configMapKeyRef:
          name: spring-app-config # the configmap this value comes from
          key: application.properties # the key to fetch
    volumeMounts:
    - name: application-config
      mountPath: "/src/main/resources/application.properties"
      readOnly: true
volumes:
  # set volumes at the pod level, then mount them into the containers inside that pod
  - name: application-config
    configMap:
      # provide the name of the configmap you want to mount
      name: spring-app-config
      # an arra of keys from the configmap to create as files
      items:
        -key: "application.properties"
