apiVersion: v1
kind: Service
metadata:
  name: petclinic-application
  namespace: petclinic
  labels:
    app: petclinic-application
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
      name: http
  selector:
    app: petclinic-application

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-application
  namespace: petclinic
  labels:
    app: petclinic-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-application
  template:
    metadata:
      labels:
        app: petclinic-application
    spec:
      containers:
        - name: petclinic
          image: thevestedleopard/springboot-docker:latest
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /src/main/resources/application.properties
            name: application-config
            readOnly: true
      volumes:
      - name: application-config
      configMap:
        name: spring-app-config
        items:
        - key: application.properties
          path: application.properties
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
