kind: Namespace
apiVersion: v1
metadata:
  name: petclinic

---
apiVersion: networking.k8s.io/v1beta1
#apiVersion: networking.k8s.io/v1 Ingress
kind: Ingress
metadata:
  name: petclinic-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: petclinic-application
          servicePort: 8080

---
apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secret
  namespace: petclinic
type: Opaque
data:
  spring.datasource.password: MTJQb3N0Z3Jlc0Ah

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

